const menu = [
  {
    id: 1,
    title: "sprouted wheat salad",
    category: "salads",
    price: 15.99,
    desc: `Calories: 186 kcal. Composition: Cherry tomatoes, dates, rocket, almond, lollo rosso. On-site service fee 20%`,
  },
  {
    id: 2,
    title: "anahata",
    category: "salads",
    price: 15.99,
    desc: `Calories: 175 kcal. Composition: Cucumber, broccoli, green apples, sprouted mong beans, lime. On-site service fee 20%`,
  },
  {
    id: 3,
    title: "beetroot salad with cashew",
    category: "salads",
    price: 15.99,
    desc: `Calories: 210 kcal. Composition: Beet leaf, beetroot, cashew, dates. On-site service fee 20%`,
  },
  {
    id: 4,
    title: "spaghetti bolognese",
    category: "dishes",
    price: 16.99,
    desc: `Calories: 227 kcal. Composition: cucumber, parsley, tomato. On-site service fee 20%`,
  },
  {
    id: 5,
    title: "butternut stuffed shells",
    category: "dishes",
    price: 21.99,
    desc: `Calories: 314 kcal. Composition: beans, pasta, sunflower seeds. On-site service fee 20%`,
  },
  {
    id: 6,
    title: "broccoli vegan pasta",
    category: "dishes",
    price: 16.99,
    desc: `Calories: 250 kcal Composition: pasta, broccoli, carrot. On-site service fee 20%`,
  },
  {
    id: 7,
    title: "kimchi bowl",
    category: "dishes",
    price: 29.99,
    desc: `Kimchi, avocado, couscous, raddish, spinach, iceberg lettuce, cauliflower, blue cabbage, cucumber`,
  },
  {
    id: 8,
    title: "Buddha Bowl",
    category: "dishes",
    price: 37.99,
    desc: `Calories: 445 kcal. Composition: Carrot, cauliflower, red bell pepper, cherry tomato, purple cabbage, broccoli, avocado, cucumber, radish, nacho sauce. On-site service fee 20%`,
  },
  {
    id: 9,
    title: "Nachos",
    category: "dishes",
    price: 29.99,
    desc: `Calories: 360 kcal Composition: cashew, red pepper, garlic, lemon, green onion, On-site service fee 20%`,
  },
  {
    id: 10,
    title: "raw chocolate balls",
    category: "desserts",
    price: 16.99,
    desc: `Calories (1 piece): 61 kcal. Composition: Cocoa beans, nuts, dates, coconut flakes. On-site service fee 20%`,
  },
  {
    id: 11,
    title: "Dried fruit dessert",
    category: "desserts",
    price: 16.99,
    desc: `Calories: 249 kcal. Composition: Nuts, dates, bananas, coconut flakes, dehydrated apricots, seasonal fruits. On-site service fee 20%`,
  },
  {
    id: 12,
    title: "truffles",
    category: "desserts",
    price: 20.99,
    desc: `Calories (1 piece): 77 kcal. Composition: Cacao, flaxseed, nut, dates. On-site service fee 20%`,
  },
  {
    id: 13,
    title: "roasted butternut salad",
    category: "salads",
    price: 13.99,
    desc: `Calories: 210 kcal. Composition: roasted butternut squash and cabbage, kale and carrot ribbons, chickpeas, a tangy vinaigrette. On-site service fee 20%`,
  },
  {
    id: 14,
    title: "smashed cucumber salad",
    category: "salads",
    price: 9.99,
    desc: `Calories: 110 kcal. Composition: cucumber, garlic, sunflower seeds. On-site service fee 20%`,
  },
  {
    id: 15,
    title: "chickpea salad",
    category: "salads",
    price: 10.99,
    desc: `Calories: 200 kcal. Composition: avocado, chickpeas, lemon, garlic. On-site service fee 20%`,
  },
  {
    id: 16,
    title: "broccoli salad",
    category: "salads",
    price: 15.99,
    desc: `Calories: 170 kcal. Composition: dried cranberries, almond, broccoli, lemon. On-site service fee 20%`,
  },
  {
    id: 17,
    title: "vegan tacos",
    category: "dishes",
    price: 21.99,
    desc: `Calories: 360 kcal Composition: tomato, red pepper, garlic, lemon, green onion, On-site service fee 20%`,
  },
  {
    id: 18,
    title: "peanut butter cookies",
    category: "desserts",
    price: 14.99,
    desc: `Calories (1 piece): 77 kcal. Composition: Cacao, flaxseed, nut, peanut. On-site service fee 20%`,
  },
  {
    id: 19,
    title: "almond cookies",
    category: "desserts",
    price: 20.99,
    desc: `Calories (1 piece): 97 kcal. Composition: almond flour, maple syrup, tahini, pomegranate. On-site service fee 20%`,
  },
  {
    id: 20,
    title: "oatmeal bites",
    category: "desserts",
    price: 11.99,
    desc: `Calories (1 piece): 71 kcal. Composition: chocolate chips, coconut, oats, vanilla. On-site service fee 20%`,
  },
  {
    id: 21,
    title: "apple cookies",
    category: "desserts",
    price: 13.99,
    desc: `Calories (1 piece): 47 kcal. Composition: apple, oat, nut, honey. On-site service fee 20%`,
  },
];
export default menu;
